# Generated by Django 5.1.1 on 2024-10-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_problemlevel_problemtype_alter_contact_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemlevel',
            name='position_type_id',
        ),
        migrations.AddField(
            model_name='problemlevel',
            name='problem_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.problemtype'),
        ),
    ]
