# Generated by Django 5.1.1 on 2024-10-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_problemlevel_position_type_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemlevel',
            old_name='problem_type_id',
            new_name='problem_type',
        ),
    ]
