# Generated by Django 5.1.1 on 2024-10-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_problem_type_id_problemlevel_problem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemlevel',
            name='symbol_position',
        ),
    ]
