# Generated by Django 5.1.1 on 2024-10-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_problemlevel_symbol_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time_bound',
            field=models.DurationField(),
        ),
    ]
