# Generated by Django 5.1.1 on 2024-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_problem_time_bound'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
