# Generated by Django 5.1.1 on 2024-10-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_problem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemscoremapping',
            name='student_answered',
            field=models.IntegerField(null=True),
        ),
    ]
